### ISSUE TITLE
Switch mainnet from hosted to decentralized

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#2018]
- [x] #2022
- [x] Curate our subgraph
- [ ] Query fee budget funded (is this on polygon? watch video)
  - [ ] Bridge to polygon
- [ ] Generate API keys
  - [ ] One for front-end
  - [ ] One for jobs
  - [ ] One for tools
  - [ ] One for each external partner (need to communicate with existing users)
- [ ] #2024
- [ ] Communicate to projects using our subgraph the new endpoint and to contact us for API key
- [ ] Can we rate limit API usage?
- [ ] #2025

https://www.loom.com/share/a81de6ef11d64c62872ea210c58c6af5

**Comment by plor** [comment]
Need to ask how to "delete" hosted subgraph. Or do we just need to use the new endpoint?
